-- Run basic tests
local require = require(game:GetService("ReplicatedStorage"):WaitForChild("Framework"))
local Ambassador = require("Ambassador")
wait(0.1)
print("Creating a new remote")
local myRemote = Ambassador.new("test123")
print("Firing")
local a,value = myRemote:SendAsync("test"):await()
print("Fired")
print(a, value)